version: "3"
services:
    web:
        restart: always
        image: villa01/mern-app-be
        ports:
            - '5000:5000'
        links:
            - mongo
            - react-app
    mongo:
        container_name: mongoadatabase
        image: mongo:latest
        ports:
            - '27018:27017'
        logging:
            driver: none
    react-app:
        image: villa01/mern-app
        stdin_open: true
        ports:
            - '3000:3000'
        
